config/routes.rb
Rails.application.routes.draw do

  # root / landing page / dashboard
  root 'welcome#index'
  get 'welcome/index'
  get 'dashboard', to: redirect('dashboard/index')
  get 'dashboard/index'
  get 'dashboard/new_discussion'


  # session
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy'

  # other resources

  resources :users
  get 'signup' => 'users#signup'
  post 'signup' => 'users#create'

  resources :topics, :only => [:new, :create]

  namespace :api do
    namespace :v1 do
      jsonapi_resources :articles
    end
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :posts, dependent: :nullify
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :author
    belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :delete_all
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, confirmation: true, on: :create

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }

  has_many :topics, dependent: :nullify
  has_many :authors, dependent: :nullify

  def display_username
    if username.nil?
      email.gsub(/\@.*/, '')
    else
      username
    end
  end
  alias_method :name, :display_username

end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < JSONAPI::ResourceController
#  def index
#    @articles = Article.all
#    render :json => @articles.to_json
#  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper

  def logged_in_user
    redirect_to root_url unless logged_in
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :logged_in_user

  def index
    @user = current_user
    @current_topic = find_current_topic
  end

  def new_discussion
    @user = current_user
    @current_topic = Topic.new

    render :index
  end

  private

  def find_current_topic

    unless params[:topic_id].nil?
      current_user.topics.find(params[:topic_id])
    else
      current_user.topics.first
    end

  rescue
    current_user.topics.first
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  layout "landing" 
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to dashboard_index_url
    else
      flash.now[:error] = '<h3>Invalid email/password</h3><p>Please verify your credentials</p>'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
  end

  def create
    params[:topic].permit!
    @topic = Topic.new(params[:topic])
    @topic.user = current_user
    @topic.save!
    redirect_to controller: :dashboard, action: :index, topic_id: @topic.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "application", :except => [:signup, :create]
  layout "landing", :only => [:signup, :create]

  def signup
  end

  def create
    @user = User.new(signup_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Knt-Discuss! :-)"
      redirect_to dashboard_index_url
    else
      flash.now[:error] = "Something's wrong, please verify your submission"
      render 'signup'
    end
  end

  def show
  end

  private

    def signup_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "landing"

  def index
    if logged_in
      redirect_to dashboard_index_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def activate_menu(menu)
    'active' if 
      (menu == 'profile'   && params[:controller] == 'users') ||
      (menu == 'dashboard' && params[:controller] != 'users')
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

    def activate_current_topic(topic, current_topic)
        'email-item-current' if topic.id == current_topic.id
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<div id="list" class="pure-u-1">

    <% @user.topics.each do |topic| %>

        <div class="email-item pure-g <%= activate_current_topic(topic, @current_topic) %>">
            <!--div class="pure-u">
                <img width="64" height="64" alt="Discuss avatar" class="email-avatar" src="no.png" />
            </div-->
            <div class="pure-u-3-4">
                <%= link_to(dashboard_index_path(topic_id: topic.id)) do %>
                    <h5 class="email-name"><%= topic.host %></h5>
                    <h4 class="email-subject"><%= topic.title %></h4>
                <!--p class="email-desc">desc</p-->
                <% end %>
            </div>
        </div>

    <% end %>
<!--div class="email-item pure-g>">
            <div class="pure-u-3-4">
                <a href="">
                    <h5 class="email-name">topic</h5>
                    <h4 class="email-subject">Title</h4>
                </a>
            </div>
        </div-->
    <div class="email-item new">
        <%= link_to "New Discussion", dashboard_new_discussion_path, class: "primary-button pure-button" %>
    </div>
</div>

<div id="topic" class="">
    <% unless @current_topic.nil? %>
        <% if @current_topic.id.nil? %>
            <%= render partial: 'topics/form', object: @current_topic, as: :topic %>
        <% else %>
            <%= render @current_topic unless @current_topic.nil? %>
        <% end %>
    <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KntDiscuss - <%= yield(:title) %></title>

  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <%= stylesheet_link_tag "https://unpkg.com/purecss@0.6.2/build/pure-min.css", { crossorigin: "anonymous", integrity: "sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD" } %>

  <!--[if lte IE 8]>
    <%= stylesheet_link_tag "https://unpkg.com/purecss@0.6.2/build/grids-responsive-old-ie-min.css" %>
    <%= stylesheet_link_tag "pure/application/email-old-ie" %>
  <![endif]-->
  <!--[if gt IE 8]><!-->
    <%= stylesheet_link_tag"https://unpkg.com/purecss@0.6.2/build/grids-responsive-min.css" %>
    <%= stylesheet_link_tag "pure/application/email" %>
  <!--<![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body id="knt-discuss">

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <div id="layout" class="content pure-g">
    <div id="nav" class="pure-u">
      <span class="pure-menu-heading">
        <%= current_user.name %>
      </span>
      <a href="#" class="nav-menu-button">Menu</a>

      <div class="nav-inner">
        <div class="pure-menu">
          <ul class="pure-menu-list">
            <li class="pure-menu-item">
              <a href="<%= dashboard_index_url %>" class="pure-menu-link <%= activate_menu('dashboard') %>">
                <span class="email-label-work"></span>Dashboard
              </a>
            </li>
            <li class="pure-menu-item">
              <a href="<%= user_path(current_user) %>" class="pure-menu-link <%= activate_menu('profile') %>">
                <span class="email-label-personal"></span>Profile
              </a>
            </li>
            <li class="pure-menu-item">
              <a href="<%= logout_path %>" class="pure-menu-link">
                <span class="email-label-caution"></span>Logout
              </a>
            </li>
          </ul>
        </div>
        <button class="primary-button pure-button">New Discussion</button>

        <div class="pure-menu">
          <ul class="pure-menu-list">
            <li class="pure-menu-heading">Favorites</li>
            <li class="pure-menu-item">
              <a href="#" class="pure-menu-link">
                Personal
              </a>
            </li>
          </ul>
        </div>

      </div>

    </div>

    <div id="main" class="pure-u-1">
      <%= yield %>
    </div>

  </div>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KntDiscuss - <%= yield(:title) %></title>

  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <%= stylesheet_link_tag "https://unpkg.com/purecss@0.6.2/build/pure-min.css", { crossorigin: "anonymous", integrity: "sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD" } %>

  <!--[if lte IE 8]>
    <%= stylesheet_link_tag "https://unpkg.com/purecss@0.6.2/build/grids-responsive-old-ie-min.css" %>
    <%= stylesheet_link_tag "pure/landing/blog-old-ie" %>
  <![endif]-->
  <!--[if gt IE 8]><!-->
    <%= stylesheet_link_tag"https://unpkg.com/purecss@0.6.2/build/grids-responsive-min.css" %>
    <%= stylesheet_link_tag "pure/landing/blog" %>
  <!--<![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
      <div class="header">
        <h1 class="brand-title">
          <%= link_to "Knt-Discuss", root_path %>
        </h1>
        <h2 class="brand-tagline">A minimalist discussion engine</h2>

        <nav class="nav">
          <ul class="nav-list">
            <li class="nav-item">
              <%= link_to "Sign in", login_path, :class => "pure-button" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", signup_path, :class => "pure-button button-signup" %>
            </li>
          </ul>
        </nav>
      </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
      <div>
          <%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>

</body>
</html>

app/views/session/new.html.erb
<% provide(:title, "Sign in") %>

<div class="posts">
  <section class="post">
    <div class="post-description">
      
      <% flash.each do |message_type, message| %>
        <div class="message <%= message_type %>">
            <%= sanitize(message) %>
        </div>
      <% end %>

      <%= form_for(:session, url: login_path, html: { class: "pure-form pure-form-aligned" }) do |f| %>
        <fieldset>
          <legend><strong>Sign in</strong> to Knt-Discuss</legend>
          <div class="pure-control-group">
            <%= f.label :email, "Email address" %>
            <%= f.email_field :email %>
          </div>

          <div class="pure-control-group">
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>

          <div class="pure-controls">
            <%= f.submit "Sign in", :class => 'pure-button pure-button-primary' %>
          </div>
        </fieldset>  
      <% end %>
    </div>
  </section>
</div>

app/views/topics/_form.html.erb
<%= form_for topic, url: {controller: :topics, action: :create} do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :url %>
  <%= f.submit "Create" %>
<% end %>

app/views/topics/_topic.html.erb
<h1><%= topic.title %></h1>

app/views/users/show.html.erb
<div id="list" class="pure-u-1">
      
    <div class="email-item pure-g">
        <div class="pure-u-3-4">
            <h4 class="email-subject">Subject</h4>
            <p class="email-desc">desc</p>
        </div>
    </div>

</div>

users::show.html.erb

app/views/users/signup.html.erb
<% provide(:title, "Sign up") %>

<div class="posts">
  <section class="post">
    <div class="post-description">
      
      <% flash.each do |message_type, message| %>
        <div class="message <%= message_type %>">
            <%= sanitize(message) %>
        </div>
      <% end %>

      <%= form_for(:user, url: signup_path, html: { class: "pure-form pure-form-aligned" }) do |f| %>
        <fieldset>
          <legend><strong>Sign up</strong> to Knt-Discuss</legend>
          <div class="pure-control-group">
            <%= f.label :email, "Email address" %>
            <%= f.email_field :email %>
          </div>

          <div class="pure-control-group">
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>

          <div class="pure-control-group">
            <%= f.label :password_confirmation, "Confirm password" %>
            <%= f.password_field :password_confirmation %>
          </div>

          <div class="pure-controls">
            <%= f.submit "Sign up", :class => 'pure-button pure-button-primary button-signup' %>
          </div>
        </fieldset>  
      <% end %>
    </div>
  </section>
</div>

app/views/welcome/index.html.erb
<div class="posts">
  <section class="post">
    <header>
      <!-- avatar here!
      <img
        width="48"
        height="48"
        alt="Kao ..98&#x27;s avatar"
        class="post-avatar"
        src="/"
      />
      -->
      <h2 class="post-title">Introducing Knt-Discuss</h2>
      <p class="post-meta">
        By <a href="#" class="post-author">Kao ..98</a>
      </p>
    </header>
    <div class="post-description">
      <p>
        Please welcome a brand new discussion engine: Knt-Discuss! Feel free
        to try it, registering, signing-in, loging-in, everything!
      </p>
    </div>
  </section>
</div>

<div class="posts">
  <h1 class="content-subhead">News</h1>
  <section class="post">
    <header>
      <!-- avatar here!
      <img
        width="48"
        height="48"
        alt="Kao ..98&#x27;s avatar"
        class="post-avatar"
        src="/"
      />
      -->
      <h2 class="post-title">No release yet - Nothing yet!</h2>
      <p class="post-meta">
        By <a href="#" class="post-author">Kao ..98</a> 
        - <a class="post-category post-category-design">Release</a>
      </p>
    </header>
    <div class="post-description">
      <p>
        How can you be here!?
      </p>
    </div>
  </section>
  <section class="post">
    <header>
      <!-- avatar here!
      <img
        width="48"
        height="48"
        alt="Kao ..98&#x27;s avatar"
        class="post-avatar"
        src="/"
      />
      -->
      <h2 class="post-title">No release yet - Nothing yet!</h2>
      <p class="post-meta">
        By <a href="#" class="post-author">Kao ..98</a> 
        - <a class="post-category post-category-design">Release</a>
      </p>
    </header>
    <div class="post-description">
      <p>
        How can you be here!?
      </p>
    </div>
  </section>
</div>